package com.ccit.model;

import java.util.Map;

public enum CustomerErrorConstants implements LocalError {


    //#####################业务错误码#####################

    ACCELERATION_USED_ENTRY_SHOULD_NOT_BE_REMOVED("100002", "可用入口中必须包含当前入口"),
    ACCELERATION_CHANGE_FAIL("100003", "加速业务变更失败"),

    NETWORK_USED_ENTRY_SHOULD_NOT_BE_REMOVED("100012", "可用入口中必须包含当前入口"),
    NETWORK_CHANGE_FAIL("100013", "加速业务变更失败"),

    CUSTOMER_INTERNET_CAFE_NOT_EXIST("100101", "客户不存在"),
    CUSTOMER_INTERNET_CAFE_NAME_USED("100102", "客户名称已使用"),
    CUSTOMER_INTERNET_CAFE_ZION_NAME_USED("100103", "客户关联Portal用户名已使用"),
    CUSTOMER_INTERNET_CAFE_NOT_FREED("100104", "客户正在使用中"),

    CUSTOMER_ENTERPRISE_NOT_EXIST("100111", "客户不存在"),
    CUSTOMER_ENTERPRISE_NAME_USED("100112", "客户名称已使用"),
    CUSTOMER_ENTERPRISE_SEXTANT_NAME_USED("100113", "客户关联Portal用户名已使用"),
    CUSTOMER_ENTERPRISE_NOT_FREED("100114", "客户正在使用中"),

    BOX_INTERNET_CAFE_NOT_EXIST("100271", "盒子不存在"),
    BOX_INTERNET_CAFE_SN_REPEAT("100272", "盒子序列号重复"),
    BOX_INTERNET_CAFE_SYNCHRONIZATION_FAIL("100273", "同步盒子失败"),
    BOX_INTERNET_CAFE_BANDWIDTH_MAX_NULL("100274", "盒子最大带宽为空"),
    BOX_INTERNET_CAFE_ACTIVE_ENTRY_EMPTY("100275", "盒子可用入口为空"),
    BOX_INTERNET_CAFE_OFFLINE("100276", "盒子离线"),

    BOX_ENTERPRISE_NOT_EXIST("100281", "盒子不存在"),
    BOX_ENTERPRISE_SN_REPEAT("100282", "盒子序列号重复"),
    BOX_ENTERPRISE_SYNCHRONIZATION_FAIL("100283", "同步盒子失败"),
    BOX_ENTERPRISE_BANDWIDTH_MAX_NULL("100284", "盒子最大带宽为空"),
    BOX_ENTERPRISE_ADVANCED_ENTRY_LIST_EMPTY("100285", "专家模式可用入口为空"),
    BOX_ENTERPRISE_OFFLINE("100286", "盒子离线"),
    BOX_ACTIVE_COLLECTION_EMPTY("100287", "盒子可用集合为空"),
    BOX_ENTERPRISE_SIMPLE_ENTRY_LIST_EMPTY("100288", "简易模式可用入口为空"),
    BOX_ENTERPRISE_ACCESS_USER_NAME_EMPTY("100289", "简易模式入口用户名为空"),
    BOX_ENTERPRISE_ACCESS_USER_PASSWORD_EMPTY("100301", "简易模式入口密码为空"),


    USER_NOT_EXIST("100291", "用户不存在"),
    USER_NAME_USED("100292", "用户名已使用"),
    USER_SYNCHRONIZATION_FAIL("100293", "用户同步失败"),

    BOX_NETWORK_NOT_EXIST("100301", "盒子不存在"),
    BOX_NETWORK_SN_REPEAT("100302", "盒子序列号重复"),
    BOX_NETWORK_SYNCHRONIZATION_FAIL("100303", "同步盒子失败"),
    BOX_NETWORK_BANDWIDTH_MAX_NULL("100304", "盒子最大带宽为空"),
    BOX_NETWORK_ACTIVE_ENTRY_EMPTY("100305", "盒子可用入口为空"),
    BOX_NETWORK_OFFLINE("100306", "盒子离线"),

    SERVER_NOT_EXIST("100341", "服务器不存在"),
    SERVER_NOT_FREED("100342", "服务器正在使用中"),

    ORDER_INTERNET_CAFE_NOT_EXIST("100351", "订单不存在"),
    ORDER_INTERNET_CAFE_NOT_IN_CHECKING_STATUS("100352", "订单不可以被审核"),

    ORDER_ENTERPRISE_NOT_EXIST("100361", "订单不存在"),
    ORDER_ENTERPRISE_NOT_IN_CHECKING_STATUS("100362", "订单不可以被审核"),
    ORDER_ENTERPRISE_NOT_MODIFICATION("100363", "此订单信息不能被修改"),
    ORDER_ENTERPRISE_NOT_CLOSE("100364", "此订单不能被关闭"),
    ORDER_ENTERPRISE_NOT_OPEN("100365", "此订单不能被开启"),

    ENTRY_NETWORK_NOT_EXIST("100371", "加速入口不存在"),
    ENTRY_NETWORK_NOT_FREED("100372", "加速入口正在使用中"),
    ENTRY_NETWORK_REPEAT("100373", "加速入口重复"),
    ENTRY_NETWORK_NAME_REPEAT("100374", "加速入口名称重复"),
    ENTRY_NETWORK_SYNCHRONIZATION_FAIL("100375", "加速入口同步失败"),
    ENTRY_NETWORK_IP_REPEAT("100376", "主备IP重复"),
    ENTRY_NETWORK_NOT_SYNC("100377", "该组网入口不能被下发"),

    ENTRY_IPIP_NOT_EXIST("100381", "加速入口不存在"),
    ENTRY_IPIP_NOT_FREED("100382", "加速入口正在使用中"),
    ENTRY_IPIP_REPEAT("100383", "加速入口重复"),
    ENTRY_IPIP_NAME_REPEAT("100384", "加速入口名称重复"),
    ENTRY_IPIP_SYNCHRONIZATION_FAIL("100385", "加速入口同步失败"),

    ENTRY_SHADOWSOCKS_NOT_EXIST("100391", "加速入口不存在"),
    ENTRY_SHADOWSOCKS_NOT_FREED("100392", "加速入口正在使用中"),
    ENTRY_SHADOWSOCKS_REPEAT("100393", "加速入口重复"),
    ENTRY_SHADOWSOCKS_NAME_REPEAT("100394", "加速入口名称重复"),
    ENTRY_SHADOWSOCKS_SYNCHRONIZATION_FAIL("100395", "加速入口同步失败"),
    ENTRY_SHADOWSOCKS_COMMON_IP_REPEAT("100396", "标准入口主备IP重复"),
    ENTRY_SHADOWSOCKS_COMMON_DNS_REPEAT("100397", "标准入口DNS重复"),
    ENTRY_SHADOWSOCKS_SPECIAL_IP_REPEAT("100398", "特殊入口主备IP重复"),
    ENTRY_SHADOWSOCKS_SPECIAL_DNS_REPEAT("100399", "特殊入口DNS重复"),

    ACCELERATION_TARGET_NOT_EXIST("100401", "加速目标不存在"),

    PAYMENT_ENTERPRISE_NOT_EXIST("100410", "支付信息不存在"),

    ACCELERATION_COLLECTION_REPEAT("100421", "当前加速集已存在"),
    ACCELERATION_COLLECTION_NOT_EXIST("100422", "当前加速集不存在"),
    ACCELERATION_IPSET_REPEAT("100423", "当前IPSET已存在"),
    ACCELERATION_IPSET_NOT_EXIST("100424", "当前IPSET不存在"),
    ACCELERATION_CIDR_REPEAT("100431", "当前加速集中此加速IP地址段已存在"),
    ACCELERATION_CIDR_ILLEGAL("100432", "当前加速集中此加速IP地址段校验失败"),
    ACCELERATION_DOMAIN_REPEAT("100441", "当前加速集中此域名已存在"),
    ACCELERATION_DOMAIN_ILLEGAL("100442", "当前加速集中此域名校验失败"),

    UPDATE_COLLECTION_SYNCHRONIZATION("100444", "更新加速集合同步失败"),
    DELETE_COLLECTION_SYNCHRONIZATION("100445", "删除加速集合同步失败"),
    CREATE_CIDR_SYNCHRONIZATION("100446", "新增加速IP地址段同步失败"),
    SYNC_CIDR_SYNCHRONIZATION("100447", "同步加速IP地址段同步失败"),
    DELETE_CIDR_SYNCHRONIZATION("100448", "删除加速IP地址段同步失败"),
    CREATE_DOMAIN_SYNCHRONIZATION("100449", "新增域名同步失败"),
    SYNC_DOMAIN_SYNCHRONIZATION("100450", "同步域名同步失败"),
    DELETE_DOMAIN_SYNCHRONIZATION("100451", "删除域名同步失败"),
    UPDATE_IPSET_SYNCHRONIZATION("100452", "更新加速IPSET同步失败"),
    DELETE_IPSET_SYNCHRONIZATION("100453", "删除加速IPSET同步失败"),

    NETWORK_LINK_NOT_EXIST("100501", "组网连接不存在"),
    UPDATE_NETWORK_LINK_SYNCHRONIZATION_FAIL("100502", "更新组网连接同步失败"),
    DELETE_NETWORK_LINK_SYNCHRONIZATION_FAIL("100503", "删除组网连接同步失败"),

    ENTRY_ENTERPRISE_L2TP_NOT_EXIST("100511", "加速入口不存在"),
    ENTRY_ENTERPRISE_L2TP_NOT_FREED("100512", "加速入口正在使用中"),
    ENTRY_ENTERPRISE_L2TP_REPEAT("100513", "加速入口重复"),
    ENTRY_ENTERPRISE_L2TP_NAME_REPEAT("100514", "加速入口名称重复"),
    ENTRY_ENTERPRISE_L2TP_SYNCHRONIZATION_FAIL("100515", "加速入口同步失败"),
    ENTRY_ENTERPRISE_L2TP_IP_REPEAT("100516", "主备IP重复"),
    ENTRY_L2TP_NOT_FREED("100517", "加速入口正在使用中"),
    ENTRY_ENTERPRISE_L2TP_NOT_SYNC("100518", "该入口不能被下发"),

    ACCELERATION_BOX_UPGRADE_TASK_NOT_EXIST("100531", "升级任务不存在"),
    ACCELERATION_BOX_UPGRADE_TASK_UPGRADING("100532", "该盒子正在升级中"),
    ACCELERATION_BOX_UPGRADE_TASK_UPGRADE_SUCCESS("100533", "该盒子升级成功"),
    ACCELERATION_BOX_UPGRADE_TASK_START_TIME_ILLEGAL("100534", "开始时间应大于当前时间"),
    ACCELERATION_BOX_UPGRADE_TASK_END_TIME_ILLEGAL("100535", "结束时间非法"),
    ACCELERATION_BOX_UPGRADE_TASK_START_END_TIME_ILLEGAL("100536", "开始时间与结束时间相距过短"),

    NETWORK_BOX_UPGRADE_TASK_NOT_EXIST("100541", "升级任务不存在"),
    NETWORK_BOX_UPGRADE_TASK_UPGRADING("100542", "该盒子正在升级中"),
    NETWORK_BOX_UPGRADE_TASK_UPGRADE_SUCCESS("100543", "该盒子升级成功"),
    NETWORK_BOX_UPGRADE_TASK_START_TIME_ILLEGAL("100544", "开始时间应大于当前时间"),
    NETWORK_BOX_UPGRADE_TASK_END_TIME_ILLEGAL("100545", "结束时间非法"),
    NETWORK_BOX_UPGRADE_TASK_START_END_TIME_ILLEGAL("100546", "开始时间与结束时间相距过短"),

    ACCELERATION_BOX_UPGRADE_PACKAGE_FILEMD5_EXIST("100551", "企业加速盒子升级包已存在"),
    ACCELERATION_BOX_UPGRADE_PACKAGE_UPLOAD_PATH_EMPTY("100552", "企业加速盒子升级包上传路径为空"),
    ACCELERATION_BOX_UPGRADE_PACKAGE_FILEMD5_NOT_EQUALS("100554", "企业加速盒子升级包MD5值不一致"),
    ACCELERATION_BOX_UPGRADE_PACKAGE_NOT_EXIST("100554", "企业加速盒子升级包不存在"),
    ACCELERATION_BOX_UPGRADE_PACKAGE_UPLOAD_FAIL("100555", "企业加速盒子升级包文件上传失败"),
    ACCELERATION_BOX_UPGRADE_PACKAGE_UPLOAD_DEL_FAIL("100556", "企业加速盒子升级包文件删除失败"),
    ACCELERATION_BOX_UPGRADE_PACKAGE_NOT_DELETE("100557", "企业加速盒子级包正在使用不能删除"),

    NETWORK_BOX_UPGRADE_PACKAGE_FILEMD5_EXIST("100561", "组网盒子升级包已存在"),
    NETWORK_BOX_UPGRADE_PACKAGE_UPLOAD_PATH_EMPTY("100562", "组网盒子升级包上传路径为空"),
    NETWORK_BOX_UPGRADE_PACKAGE_FILEMD5_NOT_EQUALS("10064", "组网盒子升级包MD5值不一致"),
    NETWORK_BOX_UPGRADE_PACKAGE_NOT_EXIST("100564", "组网盒子升级包不存在"),
    NETWORK_BOX_UPGRADE_PACKAGE_UPLOAD_FAIL("100565", "组网盒子升级包文件上传失败"),
    NETWORK_BOX_UPGRADE_PACKAGE_UPLOAD_DEL_FAIL("100566", "组网盒子升级包文件删除失败"),
    NETWORK_BOX_UPGRADE_PACKAGE_NOT_DELETE("100567", "组网盒子升级包正在使用不能删除"),

    ENTRY_ENTERPRISE_GROUP_NOT_EXIST("100571", "企业入口组不存在"),
    ENTRY_ENTERPRISE_GROUP_NAME_REPEAT("100572", "企业入口组名称重复"),
    ENTRY_ENTERPRISE_GROUP_REPEAT("100573", "企业入口组重复"),
    ENTRY_ENTERPRISE_GROUP_COMMON_MASTER_ENTRY_NOT_EXIST("100574", "企业入口组标准入口主入口不存在"),
    ENTRY_ENTERPRISE_GROUP_COMMON_SLAVE_ENTRY_NOT_EXIST("100575", "企业入口组标准入口备入口不存在"),
    ENTRY_ENTERPRISE_GROUP_SPECIAL_MASTER_ENTRY_NOT_EXIST("100576", "企业入口组特殊入口主入口不存在"),
    ENTRY_ENTERPRISE_GROUP_SPECIAL_SLAVE_ENTRY_NOT_EXIST("100577", "企业入口组特殊入口备入口不存在"),
    ENTRY_ENTERPRISE_GROUP_SS_SYNCHRONIZATION_FAIL("100578", "企业入口组同步失败"),
    ENTRY_ENTERPRISE_GROUP_SS_NOT_FREED("100579", "企业入口组正在使用中"),
    ENTRY_ENTERPRISE_GROUP_NOT_SYNC("100580", "该企业入口不能被下发"),

    ADN_ZONE_NOT_EXIST("100591", "云链区域不存在"),
    ADN_SERVICE_TYPE_ILLEGAL("100592", "云链服务类型非法"),
    ADN_ZONE_NOT_FREED("100593", "云链区域正在使用中"),
    ADN_ZONE_ENTRY_NOT_DELETE("100594", "区域中存在入口不能删除"),
    ADN_ZONE_CUSTOMER_ZONE_NOT_DELETE("100594", "存在用户区域关联关系不能删除"),

    ADN_ENTRY_NOT_EXIST("100601", "云链入口不存在"),
    ADN_ENTRY_ENTRY_NAME_REPEAT("100602", "云链入口名称重复"),
    ADN_ENTRY_CONTROL_IP_EXIST("100603", "云链入口控制IP已存在"),
    ADN_ENTRY_SERVER_IP_EXIST("100604", "云链入口IP已存在"),
    ADN_ENTRY_NOT_FREED("1006059", "该入口正在使用中"),

    ADN_ZONE_SYNCHRONIZATION_FAIL("100611", "同步区域失败"),
    ADN_ZONE_CUSTOMER_SYNCHRONIZATION_FAIL("100612", "同步用户区域失败"),
    ADN_ZONE_CUSTOMER_NOT_DELETE("100613", "服务中存在的区域不能删除"),

    SERVICE_4LAYER_NOT_EXIST("100621", "四层服务不存在"),
    SERVICE_4LAYER_SERVICE_ZONE_ENTRY_EMPTY("100622", "四层服务关联区域入口没有配置"),
    SERVICE_4LAYER_SERVICE_DOMAIN_EMPTY("100623", "四层服务服务域名为空"),
    SERVICE_4LAYER_SERVICE_ZONE_NOT_EXIST("100624", "四层服务区域关联关系不存在"),
    SERVICE_4LAYER_UPDATE_FAIL("100625", "四层服务同步失败"),
    SERVICE_4LAYER_REMOVE_FAIL("100626", "四层服务删除失败"),

    SERVICE_HTTP_NOT_EXIST("100631", "HTTP服务不存在"),
    SERVICE_HTTP_SERVICE_DOMAIN_EMPTY("100632", "HTTP服务服务域名为空"),
    SERVICE_HTTP_SERVICE_ZONE_NOT_EXIST("100633", "HTTP服务区域关联关系不存在"),
    SERVICE_HTTP_UPDATE_FAIL("100634", "HTTP服务同步失败"),
    SERVICE_HTTP_REMOVE_FAIL("100635", "HTTP服务删除失败"),
    SERVICE_HTTP_SERVICE_ZONE_ENTRY_EMPTY("100636", "HTTP服务关联区域入口没有配置"),

    SERVICE_3LAYER_NOT_EXIST("100631", "三层服务不存在"),
    SERVICE_3LAYER_SERVICE_ZONE_ENTRY_EMPTY("100632", "三层服务关联区域入口没有配置"),
    SERVICE_3LAYER_SERVICE_DOMAIN_EMPTY("100633", "三层服务服务域名为空"),
    SERVICE_3LAYER_SERVICE_ZONE_NOT_EXIST("100634", "三层服务区域关联关系不存在"),
    SERVICE_3LAYER_UPDATE_FAIL("100635", "三层服务同步失败"),
    SERVICE_3LAYER_REMOVE_FAIL("100636", "三层服务删除失败"),

    PERFORMANCE_TRAFFIC_SYNC_FAIL("100641", "云链服务流量同步失败"),

    ADN_CUSTOMER_DOMAIN_NOT_EXIST("100641", "云链用户域名不存在"),

    //#####################请求参数错误码#####################
    TOKEN_AUTHENTICATION_ERROR("200000", "用户认证失败"),
    PHONE_ILLEGAL("200001", "手机号格式非法"),
    TEL_ILLEGAL("200002", "电话号码格式非法"),

    IP_ILLEGAL("200006", "ip非法"),
    ETH_IF_EMPTY("200008", "以太网接口为空"),

    UPLOAD_FILE_NULL("200010", "上传的文件为空"),

    CUSTOMER_INTERNET_CAFE_NAME_EMPTY("200101", "客户名称为空"),
    CUSTOMER_INTERNET_CAFE_CONTACT_EMPTY("200102", "客户联系人为空"),
    CUSTOMER_INTERNET_CAFE_PHONE_ILLEGAL("200104", "客户电话号码非法"),
    CUSTOMER_INTERNET_CAFE_EMAIL_ILLEGAL("200105", "客户邮箱非法"),
    CUSTOMER_INTERNET_CAFE_ID_NULL("200106", "客户ID为空"),
    CUSTOMER_ZION_NAME_EMPTY("200107", "Zion关联用户名为空"),

    CUSTOMER_ENTERPRISE_NAME_EMPTY("200111", "客户名称为空"),
    CUSTOMER_ENTERPRISE_CONTACT_EMPTY("200112", "客户联系人为空"),
    CUSTOMER_ENTERPRISE_PHONE_ILLEGAL("200114", "客户电话号码非法"),
    CUSTOMER_ENTERPRISE_EMAIL_ILLEGAL("200115", "客户邮箱非法"),
    CUSTOMER_ENTERPRISE_ID_NULL("200116", "客户ID为空"),
    CUSTOMER_SEXTANT_NAME_EMPTY("200117", "Zion关联用户名为空"),

    BOX_INTERNET_CAFE_MANUFACTURER_EMPTY("200351", "盒子制造商为空"),
    BOX_INTERNET_CAFE_MODEL_EMPTY("200352", "盒子型号为空"),
    BOX_INTERNET_CAFE_SN_EMPTY("200353", "盒子序列号为空"),
    BOX_INTERNET_CAFE_WAN_COUNT_NULL("200354", "盒子WAN口数量未填写"),
    BOX_INTERNET_CAFE_WAN_COUNT_LE_ZERO("200355", "盒子WAN口数量必须大于0"),
    BOX_INTERNET_CAFE_NOT_FREED("200356", "盒子正在使用中"),

    BOX_ENTERPRISE_MANUFACTURER_EMPTY("200361", "盒子制造商为空"),
    BOX_ENTERPRISE_MODEL_EMPTY("200362", "盒子型号为空"),
    BOX_ENTERPRISE_SN_EMPTY("200363", "盒子序列号为空"),
    BOX_ENTERPRISE_WAN_COUNT_NULL("200364", "盒子WAN口数量未填写"),
    BOX_ENTERPRISE_WAN_COUNT_LE_ZERO("200365", "盒子WAN口数量必须大于0"),
    BOX_ENTERPRISE_NOT_FREED("200366", "盒子正在使用中"),

    USER_NAME_EMPTY("200371", "用户名为空"),
    USER_REAL_NAME_EMPTY("200372", "用户姓名为空"),
    USER_ROLE_EMPTY("200373", "用户角色为空"),
    USER_PASSWORD_EMPTY("200374", "用户密码为空"),
    USER_PASSWORD_CONFIRM_EMPTY("200374", "用户重复密码为空"),
    USER_PASSWORD_NOT_EQUALS("200375", "两次密码不一致"),

    BOX_NETWORK_MANUFACTURER_EMPTY("200381", "盒子制造商为空"),
    BOX_NETWORK_MODEL_EMPTY("200382", "盒子型号为空"),
    BOX_NETWORK_SN_EMPTY("200383", "盒子序列号为空"),
    BOX_NETWORK_WAN_COUNT_NULL("200384", "盒子WAN口数量未填写"),
    BOX_NETWORK_WAN_COUNT_LE_ZERO("200385", "盒子WAN口数量必须大于0"),
    BOX_NETWORK_NOT_FREED("200386", "盒子正在使用中"),
    BOX_NETWORK_ACCESS_USERNAME_EMPTY("200387", "盒子接入用户名为空"),
    BOX_NETWORK_ACCESS_PASSWORD_EMPTY("200388", "盒子接入密码为空"),
    BOX_NETWORK_USED_ENTRY_EMPTY("200389", "盒子当前入口为空"),

    SERVER_MGMT_IP_EMPTY("200391", "服务器管理ip为空"),
    SERVER_MGMT_IP_ILLEGAL("200392", "服务器管理ip非法"),
    SERVER_ENTRY_IP_EMPTY("200393", "服务器接入ip为空"),
    SERVER_ENTRY_IP_ILLEGAL("200394", "服务器接入ip非法"),
    SERVER_STATUS_SYNCHRONIZATION_FAIL("200395", "获取服务器状态失败"),

    ENTRY_IPIP_NAME_EMPTY("200431", "加速入口名称为空"),
    ENTRY_IPIP_IP_EMPTY("200432", "加速入口ip为空"),
    ENTRY_IPIP_IP_ILLEGAL("200433", "加速入口ip非法"),

    ENTRY_ENTERPRISE_SHADOWSOCKS_NAME_EMPTY("200441", "企业入口名称为空"),
    ENTRY_ENTERPRISE_SHADOWSOCKS_IP_EMPTY("200442", "企业入口ip为空"),
    ENTRY_ENTERPRISE_SHADOWSOCKS_IP_ILLEGAL("200443", "企业入口ip非法"),
    ENTRY_ENTERPRISE_SHADOWSOCKS_PORT_NULL("200444", "企业入口端口为空"),
    ENTRY_ENTERPRISE_SHADOWSOCKS_PORT_ILLEGAL("200445", "企业入口端口非法"),
    ENTRY_ENTERPRISE_SHADOWSOCKS_DNS_EMPTY("200446", "企业入口dns为空"),
    ENTRY_ENTERPRISE_SHADOWSOCKS_DNS_ILLEGAL("200447", "企业入口dns非法"),
    ENTRY_ENTERPRISE_SHADOWSOCKS_PASSWORD_EMPTY("200448", "企业入口密码为空"),

    ENTRY_ENTERPRISE_GROUP_SS_NAME_EMPTY("200461", "企业入口组名称为空"),
    ENTRY_ENTERPRISE_GROUP_SS_DESCRIPTION_EMPTY("200462", "企业入口组备注为空"),
    ENTRY_ENTERPRISE_GROUP_SS_COMMON_MASTER_EMPTY("200463", "企业入口组标准入口主入口为空"),
    ENTRY_ENTERPRISE_GROUP_SS_COMMON_SLAVE_EMPTY("200464", "企业入口组标准入口备入口为空"),
    ENTRY_ENTERPRISE_GROUP_SS_SPECIAL_MASTER_EMPTY("200465", "企业入口组特殊入口主入口为空"),
    ENTRY_ENTERPRISE_GROUP_SS_SPECIAL_SLAVE_EMPTY("200466", "企业入口组特殊入口备入口为空"),

    ACCELERATION_TARGET_CIDR_ILLEGAL("200475", "加速目标格式错误"),

    PAYMENT_ENTERPRISE_BILLING_DATE_NULL("200476", "账单日为空"),
    PAYMENT_ENTERPRISE_PAYMENT_DATE_NULL("200477", "账单日支付日期为空"),
    PAYMENT_ENTERPRISE_AMOUNT_ILLEGAL("200478", "金额格式非法"),
    PAYMENT_ENTERPRISE_OPERATOR_NULL("200479", "经办人为空"),

    ACCELERATION_COLLECTION_NAME_NULL("200480", "加速集合名称为空"),
    ACCELERATION_IPSET_NAME_NULL("200481", "IPSET名称为空"),
    ACCELERATION_IPSET_ACCELERATE_MODE_NULL("200482", "IPSET加速模式为空"),
    ACCELERATION_IPSET_PORT_ILLEGAL("200483", "IPSET 匹配端口非法"),
    ACCELERATION_IPSET_NAME_ILLEGAL("200484", "IPSET 名称非法"),
    ACCELERATION_CIDR_ENTERPRISE_START_PORT_ILLEGAL("200485", "开始端口非法"),
    ACCELERATION_CIDR_ENTERPRISE_END_PORT_ILLEGAL("200486", "结束端口非法"),
    ACCELERATION_CIDR_ENTERPRISE_PORT_RANGE_ILLEGAL("200487", "端口范围非法"),
    ACCELERATION_CIDR_ENTERPRISE_ILLEGAL("200488", "加速地址非法"),
    CIDR_ENTERPRISE_ILLEGAL("200489", ""),
    ACCELERATION_DOMAIN_ENTERPRISE_ILLEGAL("200490", "域名非法"),
    DOMAIN_ENTERPRISE_ILLEGAL("200491", ""),
    ACCELERATION_COLLECTION_TYPE_NULL("200492", "加速集合类型为空"),
    ACCELERATION_COLLECTION_MODE_NULL("200493", "加速集合加速模式为空"),

    NETWORK_LINK_BANDWIDTH_NULL("200493", "组网连接带宽为空"),
    NETWORK_LINK_LIST_NULL("200494", "组网连接列表为空"),
    NETWORK_LINK_BOX_ID_LEFT_NULL("200495", "组网连接盒子ID为空"),
    NETWORK_LINK_CONNECT_IP_LEFT_NULL("200496", "组网连接盒子连接IP为空"),
    NETWORK_LINK_BOX_ID_RIGHT_NULL("200497", "组网连接盒子ID为空"),
    NETWORK_LINK_CONNECT_IP_RIGHT_NULL("200498", "组网连接盒子连接IP为空"),
    NETWORK_LINK_ALIAS_NULL("200499", "组网连接名称为空"),
    NETWORK_LINK_USER_ID_NULL("200501", "组网连接用户ID为空"),
    NETWORK_LINK_LATENCY_NULL("200502", "组网连接延迟为空"),
    NETWORK_LINK_LOSS_RATE_NULL("200503", "组网连接丢包率为空"),
    NETWORK_LINK_HEARTBEAT_TIME_NULL("200504", "组网连接心跳时间为空"),
    NETWORK_LINK_STATUS_NULL("200505", "组网连接状态为空"),
    NETWORK_LINK_ENABLE_NULL("200506", "组网连接是否可用为空"),

    ENTRY_NETWORK_NAME_EMPTY("200601", "组网入口名称为空"),
    ENTRY_NETWORK_IP_EMPTY("200602", "组网入口IP地址为空"),
    ENTRY_NETWORK_IP_ILLEGAL("200603", "组网入口IP地址非法"),
    ENTRY_NETWORK_OPERATORS1_EMPTY("200604", "组网入口IP1运营商为空"),
    ENTRY_NETWORK_OPERATORS2_EMPTY("200604", "组网入口IP2运营商为空"),

    ENTRY_ENTERPRISE_L2TP_NAME_EMPTY("200701", "企业加速入口名称为空"),
    ENTRY_ENTERPRISE_L2TP_IP_EMPTY("200702", "企业加速入口IP地址为空"),
    ENTRY_ENTERPRISE_L2TP_IP_ILLEGAL("200703", "企业加速入口IP地址非法"),

    ACCELERATION_BOX_UPGRADE_TASK_START_TIME_NULL("200711", "企业升级任务开始时间为空"),
    ACCELERATION_BOX_UPGRADE_TASK_END_TIME_NULL("200712", "企业升级任务结束时间为空"),
    ACCELERATION_BOX_UPGRADE_TASK_TASK_TYPE_NULL("200713", "企业升级任务任务类型为空"),
    ACCELERATION_BOX_UPGRADE_TASK_PACKAGE_ID_NULL("200714", "企业升级任务包ID为空"),
    ACCELERATION_BOX_UPGRADE_TASK_BOX_ID_NULL("200715", "企业升级任务盒子ID为空"),

    NETWORK_BOX_UPGRADE_TASK_START_TIME_NULL("200721", "企业升级任务开始时间为空"),
    NETWORK_BOX_UPGRADE_TASK_END_TIME_NULL("200722", "企业升级任务结束时间为空"),
    NETWORK_BOX_UPGRADE_TASK_TASK_TYPE_NULL("200723", "企业升级任务任务类型为空"),
    NETWORK_BOX_UPGRADE_TASK_PACKAGE_ID_NULL("200724", "企业升级任务包ID为空"),
    NETWORK_BOX_UPGRADE_TASK_BOX_ID_NULL("200725", "企业升级任务盒子ID为空"),

    ACCELERATION_BOX_UPGRADE_PACKAGE_VERSION_NULL("200801", "企业加速盒子升级包版本为空"),
    ACCELERATION_BOX_UPGRADE_PACKAGE_SUITABLE_VERSION_NULL("200802", "企业加速盒子升级包使用版本为空"),
    ACCELERATION_BOX_UPGRADE_PACKAGE_FILEMD5_NULL("200803", "企业加速盒子升级包文件MD5为空"),
    ACCELERATION_BOX_UPGRADE_PACKAGE_DOWNLOAD_USERNAME_NULL("200804", "企业加速盒子升级包下载用户名为空"),
    ACCELERATION_BOX_UPGRADE_PACKAGE_DOWNLOAD_PASSWORD_NULL("200805", "企业加速盒子升级包下载密码为空"),

    NETWORK_BOX_UPGRADE_PACKAGE_VERSION_NULL("200811", "组网盒子升级包版本为空"),
    NETWORK_BOX_UPGRADE_PACKAGE_SUITABLE_VERSION_NULL("200812", "组网盒子升级包使用版本为空"),
    NETWORK_BOX_UPGRADE_PACKAGE_FILEMD5_NULL("200813", "组网盒子升级包文件MD5为空"),
    NETWORK_BOX_UPGRADE_PACKAGE_DOWNLOAD_USERNAME_NULL("200814", "组网盒子升级包下载用户名为空"),
    NETWORK_BOX_UPGRADE_PACKAGE_DOWNLOAD_PASSWORD_NULL("200815", "组网盒子升级包下载密码为空"),

    ADN_ZONE_NAME_NULL("200821", "云链区域名称为空"),
    ADN_ZONE_TYPE_NULL("200822", "云链区域类型为空"),
    ADN_ZONE_LONGITUDE_NULL("200823", "云链区域经度为空"),
    ADN_ZONE_LATITUDE_NULL("200824", "云链区域纬度为空"),

    ADN_ENTRY_ENTRY_NAME_NULL("200831", "云链入口名称为空"),
    ADN_ENTRY_ENTRY_TYPE_NULL("200832", "云链入口类型为空"),
    ADN_ENTRY_CONTROL_IP_NULL("200833", "云链入口控制IP为空"),
    ADN_ENTRY_CONTROL_IP_ILLEGAL("200834", "云链入口控制IP非法"),
    ADN_ENTRY_CONTROL_PORT_NULL("200835", "云链入口控制端口为空"),
    ADN_ENTRY_CONTROL_PORT_ILLEGAL("200836", "云链入口控制端口非法"),
    ADN_ENTRY_SERVER_IP_NULL("200837", "云链入口服务IP为空"),
    ADN_ENTRY_SERVER_IP_ILLEGAL("200838", "云链入口服务IP非法"),
    ADN_ENTRY_ZONE_ID_NULL("200839", "云链入口区域ID为空"),

    BEGIN_TIME_ILLEGAL("200841", "开始时间非法"),
    INTERVAL_ILLEGAL("200842", "间隔参数非法"),

    DICTIONARY_NOT_EXIST("100001", "数据字典不存在");


    private String code;

    private String message;

    private Map<String, Object> errorParams;


    CustomerErrorConstants(String code, String message) {
        this.code = code;
        this.message = message;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public Map<String, Object> getErrorParams() {
        return errorParams;
    }

    public LocalError setErrorParams(Map<String, Object> errorParams) {
        this.errorParams = errorParams;
        return this;
    }

    public String toString() {
        return "[" + code + "] " + message;
    }


    public static void main(String[] args) {
        for (CustomerErrorConstants error : CustomerErrorConstants.values()) {
//            if (error.getCode().startsWith("2")) {
//                System.out.println(String.format("| %s  | %s  |", error.getCode(), error.getMessage()));
//            }


            if (error.getMessage().contains("OF")) {
                System.out.println(String.format("%s|%s", error.getCode(), error.getMessage()));
            }
        }
    }

}
